framework:
    default_locale: fr

    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en_US
            - fr_FR
            - ar_AR
        providers:
