controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

products:
    path: /products
    controller: App\Controller\ProductController::index

change_locale:
    path: /change-locale
    controller: App\Controller\LocaleController::changeLocale
    methods: POST
